--CREATE DATABASE RaceDayDB;

--CREATE TABLE ROLES ( 
--ROLEID INT IDENTITY(1,1) PRIMARY KEY,
--ROLENAME VARCHAR(20) NOT NULL UNIQUE
--);

--CREATE TABLE USERS (
--USERID INT IDENTITY(1,1) PRIMARY KEY,
--ROLEID INT NOT NULL,
--FULLNAME VARCHAR(100) NOT NULL,
--EMAIL VARCHAR(150) NOT NULL UNIQUE,
--PASSWORDHASH VARCHAR(255) NOT NULL,
--PHONENUMBER VARCHAR(20) NULL,
--CREATEDAT DATETIME NOT NULL DEFAULT GETDATE(),
--CONSTRAINT FK_USER_ROLES FOREIGN KEY (ROLEID) REFERENCES ROLES(ROLEID)
--);

--CREATE TABLE EVENTS (
--  EVENTID INT IDENTITY(1,1) PRIMARY KEY,
--  ORGANISERID INT NOT NULL,
--  EVENTNAME VARCHAR(150) NOT NULL,
--  DESCRIPTION VARCHAR(1000) NULL,
--  EVENTDATE DATETIME NOT NULL,
--  LOCATION VARCHAR(150) NOT NULL,
--  DISTANCE DECIMAL(6,2) NOT NULL,
--  EVENTTYPE VARCHAR(20) NOT NULL,
--  ROUTEINFO VARCHAR(1000) NULL,
--  CREATEDAT DATETIME NOT NULL DEFAULT GETDATE(),
--  CONSTRAINT FK_EVENTS_USERS FOREIGN KEY (ORGANISERID) REFERENCES USERS(USERID)
--);

--CREATE TABLE CATEGORIES (
--  CATEGORYID INT IDENTITY(1,1) PRIMARY KEY,
--  EVENTID INT NOT NULL,
--  CATEGORYNAME VARCHAR(100) NOT NULL,
--  CATEGORYTYPE VARCHAR(20) NOT NULL,
--  DISTANCEKM DECIMAL(6,2) NULL,
--  MINAGE INT NULL,
--  MAXAGE INT NULL,
--  PRICE DECIMAL(8,2) NOT NULL DEFAULT 0,
--  MAXPARTICIPANTS INT NULL,
--  CONSTRAINT FK_CATEGORIES_EVENTS FOREIGN KEY (EVENTID) REFERENCES EVENTS(EVENTID)
--);

--CREATE TABLE ENROLMENTS (
--  ENROLMENTID INT IDENTITY(1,1) PRIMARY KEY,
--  PARTICIPANTID INT NOT NULL,
--  CATEGORYID INT NOT NULL, 
--  ENROLMENTDATE DATETIME NOT NULL DEFAULT GETDATE(),
--  STATUS VARCHAR(20) NOT NULL DEFAULT 'CONFIRMED',
--  CONSTRAINT FK_ENROLMENTS_USERS FOREIGN KEY (PARTICIPANTID) REFERENCES USERS(USERID),
--  CONSTRAINT FK_ENROLMENTS_CATEGORIES FOREIGN KEY (CATEGORYID) REFERENCES CATEGORIES(CATEGORYID)
--);

--CREATE TABLE RESULTS (
--  RESULTID INT IDENTITY(1,1) PRIMARY KEY,
--  ENROLMENTID INT NOT NULL UNIQUE,
--  FINISHTIME TIME NULL,
--  POSITION INT NULL,
--  STATUS VARCHAR(20) NOT NULL DEFAULT 'FINISHED',
--  CONSTRAINT FK_RESULTS_ENROLMENTS FOREIGN KEY (ENROLMENTID) REFERENCES ENROLMENTS(ENROLMENTID)
--);

