--CREATE DATABASE RaceDayDB;

--CREATE TABLE ROLES ( 
--ROLEID INT IDENTITY(1,1) PRIMARY KEY,
--ROLENAME VARCHAR(20) NOT NULL UNIQUE
--);

--CREATE TABLE USERS (
--USEID INT IDENTITY(1,1) PRIMARY KEY,
--ROLEID INT NOT NULL,
--FULLNAME VARCHAR(100) NOT NULL,
--EMAIL VARCHAR(150) NOT NULL UNIQUE,
--PASSWORDHASH VARCHAR(255) NOT NULL,
--PHONENUMBER VARCHAR(20) NULL,
--CREATEDAT DATETIME NOT NULL DEFAULT GETDATE(),
--CONSTRAINT FK_USER_ROLES FOREIGN KEY (ROLEID) REFERENCES ROLES(ROLEID)
--);

--CREATE TABLE CATEGORIES (
--  CATEGORYID INT IDENTITY(1,1) PRIMARY KEY,
--  EVENTID INT NOT NULL,
--  CATEGORYNAME VARCHAR(100) NOT NULL,
--  CATEGORYTYPE VARCHAR(20) NOT NULL,
--  DISTANCEKM DECIMAL(6,2) NULL,
--  MINAGE INT NULL,
--  MAXAGE INT NULL,
--  PRICE DECIMAL(8,2) NOT NULL DEFAULT 0,
--  MAXPARTICIPANTS INT NULL,
--  CONSTRAINT FK_CATEGORIES_EVENTS FOREIGN KEY (EVENTID) REFERENCES EVENTS(EVENTID)
--);

CREATE TABLE ENROLMENTS (
  ENROLMENTID INT IDENTITY(1,1) PRIMARY KEY,
  PARTICIPANTID INT NOT NULL,
  CATEGORYID INT NOT NULL, 
  ENROLMENTDATE DATETIME NOT NULL DEFAULT GETDATE()
);
