--CREATE DATABASE RaceDayDB;

--CREATE TABLE ROLES ( 
--ROLEID INT IDENTITY(1,1) PRIMARY KEY,
--ROLENAME VARCHAR(20) NOT NULL UNIQUE
--);

--CREATE TABLE USERS (
--USEID INT IDENTITY(1,1) PRIMARY KEY,
--ROLEID INT NOT NULL,
--FULLNAME VARCHAR(100) NOT NULL,
--EMAIL VARCHAR(150) NOT NULL UNIQUE,
--PASSWORDHASH VARCHAR(255) NOT NULL,
--PHONENUMBER VARCHAR(20) NULL,
--CREATEDAT DATETIME NOT NULL DEFAULT GETDATE(),
--CONSTRAINT FK_USER_ROLES FOREIGN KEY (ROLEID) REFERENCES ROLES(ROLEID)
--);

CREATE TABLE CATEGORIES (
  CATEGORYID INT IDENTITY(1,1) PRIMARY KEY,
  EVENTID INT NOT NULL,
  CATEGORYNAME VARCHAR(100) NOT NULL
);

